version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/mongo
      SPRING_DATA_POSTGRESQL_URI: postgresql://localhost:5433/db_auth
    depends_on:
      - db_auth
      - mongo

  db_auth:
    container_name: db_auth
    ports:
     - "5433:5432"
    environment:
      POSTGRES_DB: db_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    image: postgres:latest

  mongo:
    container_name: mongo
    ports:
      - "27017:27017"
#    environment:
#      MONGO_USERNAME: mongo
#      MONGO_PASSWORD: mongo
#      MONGO_INITDB_DATABASE: mongo
    image: mongo:latest
